// <copyright file="CloudIDs.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
#if (UNITY_ANDROID || UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
    using Internal;
    using UnityEngine;
#endif
    /// <summary>
    /// Provides access to achievement- and leaderboard IDs registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class CloudIDs
    {
        /// <summary>
        /// Contains properties that retrieves achievement IDs for the current platform.
        /// </summary>
        public static class AchievementIDs
        {
            public static string DungeonBone
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkInLWCwIIQEAIQAw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.DungeonBone.Magicbound";
#elif UNITY_EDITOR
                    return "DungeonBone";
#else
                    return string.Empty;
#endif
                }
            }

            public static string LibraryFlame
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkInLWCwIIQEAIQAg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.LibraryFlame.Magicbound";
#elif UNITY_EDITOR
                    return "LibraryFlame";
#else
                    return string.Empty;
#endif
                }
            }

            public static string FrostCrystal
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkInLWCwIIQEAIQBA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.FrostCrystal.Magicound";
#elif UNITY_EDITOR
                    return "FrostCrystal";
#else
                    return string.Empty;
#endif
                }
            }

            public static string SharpLeaf
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkInLWCwIIQEAIQBQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.SharpLeaf.Magicbound";
#elif UNITY_EDITOR
                    return "SharpLeaf";
#else
                    return string.Empty;
#endif
                }
            }

            public static string SpinningCog
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkInLWCwIIQEAIQBg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.SpinningCog.Magicbound";
#elif UNITY_EDITOR
                    return "SpinningCog";
#else
                    return string.Empty;
#endif
                }
            }

            public static string EndGame
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkInLWCwIIQEAIQBw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.EndGame.Magicbound";
#elif UNITY_EDITOR
                    return "EndGame";
#else
                    return string.Empty;
#endif
                }
            }

            public static string MonsterHunter
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "550426942108";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.MonsterHunter.Magicbound";
#elif UNITY_EDITOR
                    return "MonsterHunter";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Rich
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkInLWCwIIQEAIQCA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.Rich.Magicbound";
#elif UNITY_EDITOR
                    return "Rich";
#else
                    return string.Empty;
#endif
                }
            }

            public static string NecessaryExpenses
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkInLWCwIIQEAIQDg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.NecessaryExpenses.Magicbound";
#elif UNITY_EDITOR
                    return "NecessaryExpenses";
#else
                    return string.Empty;
#endif
                }
            }

            public static string PoweredUp
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkInLWCwIIQEAIQCQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.PoweredUp.Magicbound";
#elif UNITY_EDITOR
                    return "PoweredUp";
#else
                    return string.Empty;
#endif
                }
            }

            public static string ThatsNotHowItHappened
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkInLWCwIIQEAIQDw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.notHowItHappened.Magicbound";
#elif UNITY_EDITOR
                    return "ThatsNotHowItHappened";
#else
                    return string.Empty;
#endif
                }
            }

            public static string FlawlessBoss
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkInLWCwIIQEAIQEA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.FlawlessBoss.Magicbound";
#elif UNITY_EDITOR
                    return "FlawlessBoss";
#else
                    return string.Empty;
#endif
                }
            }

            public static string CrystalHoarder
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkInLWCwIIQEAIQCg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.CrystalHoarder.Magicbound";
#elif UNITY_EDITOR
                    return "CrystalHoarder";
#else
                    return string.Empty;
#endif
                }
            }

            public static string SpellMaster
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkInLWCwIIQEAIQCw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.SpellMaster.Magicbound";
#elif UNITY_EDITOR
                    return "SpellMaster";
#else
                    return string.Empty;
#endif
                }
            }

            public static string UltimateMage
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkInLWCwIIQEAIQDA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.UltimateMage.Magicbound";
#elif UNITY_EDITOR
                    return "UltimateMage";
#else
                    return string.Empty;
#endif
                }
            }
        }

        /// <summary>
        /// Contains properties that retrieves leaderboard IDs for the current platform.
        /// </summary>
        public static class LeaderboardIDs
        {
            public static string LevelReachedLeaderboard
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkInLWCwIIQEAIQAA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.MagicboundLeaderBoard";
#elif UNITY_EDITOR
                    return "LevelReachedLeaderboard";
#else
                    return string.Empty;
#endif
                }
            }

            public static string MonstersDefeatedLeaderBoard
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkInLWCwIIQEAIQEQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "com.Magicbound.MonstersKilled";
#elif UNITY_EDITOR
                    return "MonstersDefeatedLeaderBoard";
#else
                    return string.Empty;
#endif
                }
            }
        }
    }
}
