// <copyright file="CloudVariables.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using CloudPrefs;

    /// <summary>
    /// Provides access to cloud variables registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class CloudVariables
    {
        private static readonly CloudCurrencyInt s_crystals = new CloudCurrencyInt("Crystals", 0, false);

        public static int Crystals
        {
            get { return s_crystals.Value; }
            set { s_crystals.Value = value; }
        }

        private static readonly CloudBool s_skinPack = new CloudBool("SkinPack", PersistenceType.Latest, false);

        public static bool SkinPack
        {
            get { return s_skinPack.Value; }
            set { s_skinPack.Value = value; }
        }

        private static readonly CloudBool s_noadsbought = new CloudBool("Noadsbought", PersistenceType.Latest, false);

        public static bool Noadsbought
        {
            get { return s_noadsbought.Value; }
            set { s_noadsbought.Value = value; }
        }

        private static readonly CloudInt s_levelReached = new CloudInt("LevelReached", PersistenceType.Latest, 0);

        public static int LevelReached
        {
            get { return s_levelReached.Value; }
            set { s_levelReached.Value = value; }
        }

        private static readonly CloudInt s_carrotMissleLevel = new CloudInt("carrotMissleLevel", PersistenceType.Latest, 0);

        public static int carrotMissleLevel
        {
            get { return s_carrotMissleLevel.Value; }
            set { s_carrotMissleLevel.Value = value; }
        }

        private static readonly CloudInt s_earShieldLevel = new CloudInt("earShieldLevel", PersistenceType.Latest, 0);

        public static int earShieldLevel
        {
            get { return s_earShieldLevel.Value; }
            set { s_earShieldLevel.Value = value; }
        }

        private static readonly CloudInt s_radishMissleLevel = new CloudInt("radishMissleLevel", PersistenceType.Latest, 0);

        public static int radishMissleLevel
        {
            get { return s_radishMissleLevel.Value; }
            set { s_radishMissleLevel.Value = value; }
        }

        private static readonly CloudInt s_kickReflectLevel = new CloudInt("kickReflectLevel", PersistenceType.Latest, 0);

        public static int kickReflectLevel
        {
            get { return s_kickReflectLevel.Value; }
            set { s_kickReflectLevel.Value = value; }
        }

        private static readonly CloudInt s_magicLaserLevel = new CloudInt("magicLaserLevel", PersistenceType.Latest, 0);

        public static int magicLaserLevel
        {
            get { return s_magicLaserLevel.Value; }
            set { s_magicLaserLevel.Value = value; }
        }

        private static readonly CloudBool s_runeFloatBought = new CloudBool("RuneFloatBought", PersistenceType.Latest, false);

        public static bool RuneFloatBought
        {
            get { return s_runeFloatBought.Value; }
            set { s_runeFloatBought.Value = value; }
        }

        private static readonly CloudBool s_runeFallBought = new CloudBool("RuneFallBought", PersistenceType.Latest, false);

        public static bool RuneFallBought
        {
            get { return s_runeFallBought.Value; }
            set { s_runeFallBought.Value = value; }
        }

        private static readonly CloudBool s_runeMagnetBought = new CloudBool("RuneMagnetBought", PersistenceType.Latest, false);

        public static bool RuneMagnetBought
        {
            get { return s_runeMagnetBought.Value; }
            set { s_runeMagnetBought.Value = value; }
        }

        private static readonly CloudBool s_runeManaBought = new CloudBool("RuneManaBought", PersistenceType.Latest, false);

        public static bool RuneManaBought
        {
            get { return s_runeManaBought.Value; }
            set { s_runeManaBought.Value = value; }
        }

        private static readonly CloudBool s_runeSpellBought = new CloudBool("RuneSpellBought", PersistenceType.Latest, false);

        public static bool RuneSpellBought
        {
            get { return s_runeSpellBought.Value; }
            set { s_runeSpellBought.Value = value; }
        }

        private static readonly CloudBool s_runeShieldBought = new CloudBool("RuneShieldBought", PersistenceType.Latest, false);

        public static bool RuneShieldBought
        {
            get { return s_runeShieldBought.Value; }
            set { s_runeShieldBought.Value = value; }
        }

        private static readonly CloudBool s_runeGreedBought = new CloudBool("RuneGreedBought", PersistenceType.Latest, false);

        public static bool RuneGreedBought
        {
            get { return s_runeGreedBought.Value; }
            set { s_runeGreedBought.Value = value; }
        }

        private static readonly CloudBool s_runeMerchatBought = new CloudBool("RuneMerchatBought", PersistenceType.Latest, false);

        public static bool RuneMerchatBought
        {
            get { return s_runeMerchatBought.Value; }
            set { s_runeMerchatBought.Value = value; }
        }

        private static readonly CloudBool s_runeDestructionBought = new CloudBool("RuneDestructionBought", PersistenceType.Latest, false);

        public static bool RuneDestructionBought
        {
            get { return s_runeDestructionBought.Value; }
            set { s_runeDestructionBought.Value = value; }
        }

        private static readonly CloudBool s_runeUnknownBought = new CloudBool("RuneUnknownBought", PersistenceType.Latest, false);

        public static bool RuneUnknownBought
        {
            get { return s_runeUnknownBought.Value; }
            set { s_runeUnknownBought.Value = value; }
        }

        private static readonly CloudInt s_monstersKilled = new CloudInt("MonstersKilled", PersistenceType.Latest, 0);

        public static int MonstersKilled
        {
            get { return s_monstersKilled.Value; }
            set { s_monstersKilled.Value = value; }
        }

        private static readonly CloudInt s_moneySpent = new CloudInt("MoneySpent", PersistenceType.Latest, 0);

        public static int MoneySpent
        {
            get { return s_moneySpent.Value; }
            set { s_moneySpent.Value = value; }
        }

        private static readonly CloudInt s_diedTimes = new CloudInt("DiedTimes", PersistenceType.Latest, 0);

        public static int DiedTimes
        {
            get { return s_diedTimes.Value; }
            set { s_diedTimes.Value = value; }
        }

        private static readonly CloudInt s_levelBoughtID = new CloudInt("levelBoughtID", PersistenceType.Latest, 0);

        public static int levelBoughtID
        {
            get { return s_levelBoughtID.Value; }
            set { s_levelBoughtID.Value = value; }
        }

        private static readonly CloudBool s_manaJarPowerUp = new CloudBool("ManaJarPowerUp", PersistenceType.Latest, false);

        public static bool ManaJarPowerUp
        {
            get { return s_manaJarPowerUp.Value; }
            set { s_manaJarPowerUp.Value = value; }
        }

        private static readonly CloudBool s_extraHeartsPowerUp = new CloudBool("ExtraHeartsPowerUp", PersistenceType.Latest, false);

        public static bool ExtraHeartsPowerUp
        {
            get { return s_extraHeartsPowerUp.Value; }
            set { s_extraHeartsPowerUp.Value = value; }
        }

        private static readonly CloudBool s_phoenixFeatherPowerUp = new CloudBool("PhoenixFeatherPowerUp", PersistenceType.Latest, false);

        public static bool PhoenixFeatherPowerUp
        {
            get { return s_phoenixFeatherPowerUp.Value; }
            set { s_phoenixFeatherPowerUp.Value = value; }
        }

        private static readonly CloudBool s_coinx2TicketPowerUp = new CloudBool("Coinx2TicketPowerUp", PersistenceType.Latest, false);

        public static bool Coinx2TicketPowerUp
        {
            get { return s_coinx2TicketPowerUp.Value; }
            set { s_coinx2TicketPowerUp.Value = value; }
        }

        private static readonly CloudBool s_portalBoostPowerUp = new CloudBool("PortalBoostPowerUp", PersistenceType.Latest, false);

        public static bool PortalBoostPowerUp
        {
            get { return s_portalBoostPowerUp.Value; }
            set { s_portalBoostPowerUp.Value = value; }
        }

        private static readonly CloudInt s_test = new CloudInt("Test", PersistenceType.Latest, 0);

        public static int Test
        {
            get { return s_test.Value; }
            set { s_test.Value = value; }
        }
    }
}
